Prevent throwing exceptions when not connected
sabuhish/fastapi-mqtt pull request #91
Opened 2024-04-03 17:42 UTC by RobertDeRose

* The methods `publish` and `unsubscribe` will throw an exception if the client is not currently connected. This adds a check to ensure that the client `is_connected` before attempting to call the underlying methods.
* The `MQTTConfig` model uses an `int` for the type for the version but did not document what the supported values are. This updates the type to be a `Literal` with supported values or `4` or `5`.

2024-04-10 02:44 UTC, RobertDeRose commented
@sabuhish Any thoughts on this PR?

Is this Project still being maintained?

2024-04-10 07:01 UTC, azogue requested changes
Hi @RobertDeRose, thanks for contributing 💪

I made some comments, but, in general, I'm not sure about this PR and what do you want to accomplish with it.

**Why try to prevent exceptions for scenarios like those?** (like, if you are not connected, of course you cannot publish!). 

**The app using this library should check if the MQTT client is connected before publishing**. And, if not, manage **its own logic** to 'postpone' / 'log-error' / whatever. 

Here, we _don't know what to do_ in those scenarios, so it's better to _fail_ (throw some exception).

As an example, imagine the fastapi app using this library has a 'buffer' of pending msgs to publish, and it tests if `mqtt.client.connected` before attempting to pub (as it should always do), or appends the msg to the pending list if not connected. When re-connecting, all pending msgs are published automatically.

That's a valid use case, but, for other apps, generated msgs while not connected may have to trigger other behaviours, like errors, notifications, etc. **Therefore, these decisions only concern the main application**, not to this client. 

But that's just my _opinionated_ view 😅, maybe @sabuhish thinks differently, or maybe I have convinced you 🤞

2024-04-10 07:01 UTC, azogue commented on fastapi_mqtt/config.py
> +    version: Literal[MQTTv311,  MQTTv50] = MQTTv50 # type: ignore
Hi @RobertDeRose, a `Literal` should be a string. In this case, those `gmqtt` constants are integers. The `type: ignore` is not a good idea IMHO. 

As `MQTTConfig` is a pydantic `BaseModel`, the solution you're looking for may be something like `version: int = Field(default=MQTTv50, ge=4, le=5)`, to validate it for the 2 permitted values 👌

2024-04-10 07:01 UTC, azogue commented on fastapi_mqtt/fastmqtt.py
> +            self._logger.debug(
Something like this **should not be hidden in a 'debug' log**. 

Before, this would raise an exception, which is something you cannot ignore (and that's GOOD). This alternative does not solve any problem, only hides bad usages from the app 😓

2024-04-10 20:38 UTC, RobertDeRose commented
@azogue I think I see your point.

I will explain my reason behind this PR and perhaps there is a better solution I am not seeing or perhaps there is something this PR could still do it to allow the workflow I was considering.

Since FastAPI introduced the new `lifespan` feature to replace the `startup` and `shutdown` I implemented using this extension by creating `startup` and `shutdown` functions that will be called before and after the `yield` in the `lifespace` functions.

What I was trying to do was allow the developer to not be concerned if MQTT is enabled or not but allow them to import and use the `mqtt` object to wrap functions with `subscribe` or call `publish` directly in a route and the MQTT parts would just be enabled or disabled whether MQTT was configured or not.

```python
"""
mqtt.py
"""
from config import settings

if settings.MQTT_BROKER_CONFIG is not None:
    logger.info("MQTT broker enabled")
    logger.debug("MQTT broker config: %s", settings.MQTT_BROKER_CONFIG)
    mqtt = MQTT(config=settings.MQTT_BROKER_CONFIG, mqtt_logger=logger)

    async def start():
        await mqtt.mqtt_startup()
        logger.info("MQTT broker started")

    async def stop():
        await mqtt.mqtt_shutdown()
        logger.info("MQTT broker stopped")
else:
    # These are no-op functions that will do nothing if MQTT is disabled but allows you to
    # use the decorator throughout the app without caring if MQTT is enabled or not
    mqtt = MQTT(config=MQTTConfig())

    async def start():
        pass

    async def stop():
        pass
```

```python
"""
lifespan.py
"""
from contextlib import asynccontextmanager

from core.lifespan_tasks import mqtt as mqtt_task


@asynccontextmanager
async def lifespan(app: FastAPI):
    await mqtt_task.start()

    yield

    await mqtt_task.stop()
```

In this way, if the no-ops are used, then the developer does not need to wrap every call with

```python
if mqtt.is_connect:
   mqtt.publish(...)
```


However, I think part of my reason for this PR was because I didn't see that calling `mqtt.subscribe`  as a decorator does not care if the client is connected or not as it just adds callbacks to a dict or similar. And afterwards I decided I could solve most of my desired pattern of use by just wrapping FastMQTT in my own class.


```python
class MQTT(FastMQTT):
    """
    A Simple wrapper around FastMQTT to prevent the throwing of exception when the MQTT Client is not yet connected.
    """
    def publish(self, message_or_topic: str, payload: Any = None, qos: int = 0, retain: bool = False, **kwargs) -> None:
        if not self.client.is_connected:
                logger.info("MQTT is not connected. Can't publishi to %s", message_or_topic)
                return None
        try:
            return super().publish(message_or_topic, payload, qos, retain, **kwargs)
        except AttributeError:
            logger.info("MQTT might not be connected, unable to publish to %s", message_or_topic)
            return None

    def unsubscribe(self, topic: str, **kwargs):
        """
        This will remove the subscription, but catch if MQTT is not yet connected.
        """
        try:
            return super().unsubscribe(topic, **kwargs)
        except AttributeError:
            return None
```

And thus with this, I could do something like what you said to just add message to a queue and add a callback that would process all message once connected if I wanted.

For my use case I was considering MQTT as a feature that could be toggled on or off and would just an **extra**.

Thanks for you well written and thought-out comments.
Perhaps I could just submit the PR to update the MQTTConfig model as you suggested and remove the rest

2024-04-11 09:40 UTC, azogue commented
Hi @RobertDeRose 

I see your point, and I think I understand it, but in reality there are multiple time windows where the MQTT client could be disconnected, like in 
- short network errors, which the `gmqtt` client usually handles very well, with quick retries
- long disconnections, which have to be managed separately, and need a full reconnection + re-subscription
- anything happening in setup/shutdown phases (:= before / after the yield in the lifespan), if it happens before the first connection or after closing it.

So, in the end, you would need 'multiple flags' to check in the app before calling publish anyway, and how to manage that complexity is out of scope of this simple wrapper, which is just the _glue_ between the gmqtt client and fastapi

In my own usage of this library, for an app running on-board in an embedded platform, where the MQTT connection is also optional (and shaky), I have to do checks like this:

```python
if (
    self.settings.mqtt_connection
    and self.app_is_running
    and (mqtt_handler := self._app_state.get(MQTTHandler)).active
):
```

before triggering the publish, and after that condition, that _active_ `mqtt_handler` will also check if it's `.connected` before the pub, doing _other things_ if not 😅

But all of that is _business logic_ which has not a place here, IMO. Here, the library has flags to check, and raises exceptions, to expose the 2 ways of work: if-else, or try/except. 

As the `.publish(...)` method returns `None`, the only way of signalling an error is with the exception, that's why I was so strongly opposed to it 😂

> Thanks for you well written and thought-out comments.

Thanks ☺️, same to you

> Perhaps I could just submit the PR to update the MQTTConfig model as you suggested and remove the rest

**That would be great** 👌

2024-05-16 09:42 UTC, azogue commented
> The MQTTConfig model uses an int for the type for the version but did not document what the supported values are. This updates the type to be a Literal with supported values or 4 or 5.

The discussed fix for this lack of validation is already included in #94 ✅

I'm closing this one, @RobertDeRose  👍

2024-05-16 09:42 UTC, closed without merging